name = "nuxt-cloudflare"
pages_build_output_dir = "dist"
compatibility_date = "2024-08-14"
7-1e4063ec38b2"

[[d1_databases]]
database_id = "1a9e1e09-f61b-49ad-b24a-82769c7beafd"
binding = "DB"
database_name = "DB"

[[env.production.d1_databases]]
database_id = "1a9e1e09-f61b-49ad-b24a-82769c7beafd"
binding = "DB"
database_name = "DB"
