name = "nuxt-cloudflare-pages.pages.dev"
main = "./.output/server/index.mjs"
compatibility_date = "2024-04-03" 

[[d1_databases]] 
binding = "DB"
database_name = "wispy-resonance-ca48-db"
database_id = "1a9e1e09-f61b-49ad-b24a-82769c7beafd"